
sudo: required
services:
  - docker


before_install:
  - docker build -t tombo28/react-test -f ./client/Dockerfile.dev ./client
  - gem install bundler
script:


after_success:
  - docker build -t tombo28/multi-client ./client
  - docker build -t tombo28/multi-nginx ./nginx
  - docker build -t tombo28/multi-server ./server
  - docker build -t tombo28/multi-worker ./worker
  - echo "$DOCKER_PASWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tombo28/multi-client
  - docker push tombo28/multi-nginx
  - docker push tombo28/multi-server
  - docker push tombo28/multi-worker